services:
  api:
    build: .
    container_name: eventos_vivos_api
    restart: unless-stopped
    network_mode: "host"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - "ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=eventosvivos_db;Username=postgres;Password=${POSTGRES_PASSWORD}"
    # Al usar network_mode: "host", el contenedor usa la red de Ubuntu directamente.
    # Así puede ver la base de datos PostgreSQL instalada en tu VPS en localhost:5432
    # y la API quedará expuesta en el puerto 8080 de la IP pública de tu servidor.
